name: Build and lint

on: 
  push:
    branches:
      - 'main'
      - 'docker/net6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Setup .NET Core SDK 6.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --WarnAsError /p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }}
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core SDK 6.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.x
    - name: Format
      run: dotnet format --verify-no-changes
  docker:
    needs: [build, lint]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    # Docker login
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
    # Buildx
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v1
    # Build & publish docker image
    - name: Build and push
      id: docker
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/deploymenttest:latest
          ghcr.io/${{ github.repository_owner }}/deploymenttest:${{ steps.gitversion.outputs.NuGetVersionV2 }}
        build-args: RELEASE_VERSION=${{ steps.gitversion.outputs.NuGetVersionV2 }}