name: Release NuGet package

on: 
  workflow_run:
    workflows: [Build and lint]
    types: [completed]
    branches: [nuget/net6]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Setup .NET Core SDK 6.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.x
    - name: Add nuget source
      run: dotnet nuget add source --username ${{ secrets.RELEASE_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/jh12/index.json"
    - name: Pack nuget
      run: dotnet pack --configuration Release /p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }}
    - name: Push nuget
      run: dotnet nuget push "DeploymentTest.Nuget/bin/Release/*.nupkg" --api-key ${{ secrets.RELEASE_PAT }} --source "github"