name: release
on:
  push:
    branches:
      - main
      - develop


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - run: |
        ls | 
        dotnet nuget add source --username ${{ secrets.RELEASE_USERNAME }} --password ${{ secrets.RELEASE_PAT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/jh12/index.json" | 
        dotnet pack --configuration Release |
        dotnet nuget push "DeploymentTest.Nuget\bin\Release\DeploymentTest.Nuget.1.0.0.nupkg" --api-key ${{ secrets.RELEASE_PAT }} --source "github"